Feat/pr page
t-yng/review-cat pull request #58
Opened 2021-08-12 11:07 UTC by mojahige

2021-08-13 14:57 UTC, t-yng commented on electron/app.ts
> +      action: 'deny',
メモ:
新くウィンドを作成しない

2021-08-13 14:59 UTC, t-yng commented on electron/app.ts
> +  mainWindow.webContents.setWindowOpenHandler((details) => {
メモ:
target=_blank or window.open でページが開かれるときの処理

2021-08-13 15:51 UTC, t-yng requested changes
確認お願いしまーす

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/GitHubAvatar/GitHubAvatar.tsx
> +  return <img className={rootStyle} alt={alt ?? ''} {...otherProps} />;
REFACTOR:
デフォルト引数を使えばスッキリ書けますよ

```typescript
export const GitHubAvatar: React.FC<Props> = ({ alt = '', ...others }) => {
  // TODO: GitHub のアバター画像、パラメータ(`s={size}`)でサイズ調整できるのでうまいこと利用したい。
  return <img className={rootStyle} alt={alt} {...others} />;
};
```

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/PullRequestItem/PullRequestItem.tsx
> +type Props = PullRequest;
REFACTOR:
オブジェクトをキーの値として受け取った方が良いですよ。
モデルの型を変更した時にこの書き方だと呼び出し側も修正する必要があったり、そもそも記述が面倒だったりします。

```typescript
type Props = {
  pullRequest: PullRequst
}
```

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/PullRequestList/PullRequestList.tsx
> +        <RepositorySection pullRequest={pr} key={pr.title ?? i} />
FIX:
この構造だと1リポジトリに複数のプルリクがあった時に表示がおかしくなる気がします。🐱

PRの一覧をリポジトリでグルーピンングして、
RepositorySection > PullRequestList > PullRequestItem の構造にする必要があるのかなと思います。

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/RepositorySection/RepositorySection.tsx
> +      </ul>
FIX:
この構造だと1リポジトリに複数のプルリクがあった時に表示がおかしくなる気がします。🐱

PRの一覧をリポジトリでグルーピンングして、
RepositorySection > PullRequestList > PullRequestItem の構造にする必要があるのかなと思います。

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/RepositorySection/styles.css.ts
> +  borderBottom: `1px solid ${themeVars.color.gray100}`,
COMMENT:
基本的にボーダーのデザインは全てこれで統一しているので、値を変数化しても良いかもです。🐱

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/RepositorySectionHeadingContent/RepositorySectionHeadingContent.tsx
> +export const RepositorySectionHeadingContent: React.FC<Repository> = ({
REFACTOR:
こういうコンポーネントは素直に `React.memo` でメモかしておいて良いです。🐱

2021-08-13 15:51 UTC, t-yng commented on renderer/src/graphql/mapper/pullRequest.ts
> +    url: pr.url ?? '',
👍🏻

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/GitHubAvatar/GitHubAvatar.tsx
> +export const GitHubAvatar: React.FC<Props> = (props) => {
REFACTOR:
このコンポーネントは `React.memo` でメモ化しといても良いかもです。🐱

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/PullRequestItem/PullRequestItem.tsx
> +export const PullRequestItem: React.FC<Props> = (props) => {
REFACTOR:
このコンポーネントは `React.memo` でメモ化しといても良いかもです。🐱

2021-08-13 15:51 UTC, t-yng commented on renderer/src/components/PullRequestItem/PullRequestItem.tsx
> +export const PullRequestItem: React.FC<Props> = (props) => {
ただ `author` がオブジェクトなので呼び出し側を少し考えないとメモ化が上手く動いてくれない可能性があるので、一旦このままの方が良いかもです。👀

2021-08-13 15:52 UTC, t-yng commented
実際に動いてる感動しました！！😊

2021-08-14 14:47 UTC, mojahige commented on renderer/src/components/PullRequestItem/PullRequestItem.tsx
> +export const PullRequestItem: React.FC<Props> = (props) => {
一旦このままにしておきます 👀

2021-08-27 14:59 UTC, t-yng approved these changes
(･ω･)b < LGTM

2021-08-27 15:00 UTC, merged