[WIP] Feature/31 select repository first
t-yng/review-cat pull request #59
Opened 2021-08-13 15:35 UTC by t-yng

2021-08-15 06:03 UTC, t-yng commented on renderer/src/theme.css.ts
> +    green: '#0A9710',
変数名 green で良いのか？？🙄

2021-08-16 10:54 UTC, mojahige commented on renderer/src/theme.css.ts
> +    green: '#0A9710',
バリエーションが増えないのであれば何か名前つけても良さそうな気はしますね 👀

2021-08-16 11:17 UTC, t-yng commented on renderer/src/theme.css.ts
> +    green: '#0A9710',
今の所は増える予定はないです。

2021-08-16 11:49 UTC, mojahige requested changes
確認お願いします 🙏

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/AccountSelect/style.css.ts
> +  width: '100%',
[IMO]
`selectButtonStyle` に `alignItems: 'center'` 追加はいかがでしょう？
文字が真ん中に揃っていないのが気になります。

![スクリーンショット 2021-08-16 19 59 33](https://user-images.githubusercontent.com/13248811/129553742-9fd19658-6310-4e19-ae39-3e8f8e489199.png)

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/AccountSelect/AccountSelect.spec.tsx
> +    it('配列先頭のアカウントが初期表示すること', () => {
[NITS]
「配列先頭のアカウントが初期表示すること」は「配列先頭のアカウントが初期表示されること」の方が良さそう。
それか「配列先頭のアカウントを初期表示すること」でしょうか。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/AccountSelect/AccountSelect.tsx
> +          </Listbox.Button>
[MUST]
やれる範囲で当たり前の a11y はやっていきたいです。
`<Listbox.Button>` にタブキーでフォーカスが当たった時にアウトラインが表示されていません。

色は現状仮なのですが、`theme.css` に書いてある `themeFocusVisibleOutline` というクラスをつけることで、`:focus-visible` の時にアウトライン代わりの装飾を付けれます。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/RepositorySearchBox/RepositorySearchBox.tsx
> +      </div>
[MUST]
やれる範囲で当たり前の a11y はやっていきたいです。
`input` にタブキーでフォーカスが当たった時にアウトラインが表示されていません。

この場合はルートの `div` 要素に装飾をつけるべきですが、`:focus-within` で実現できます。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/AccountSelect/AccountSelect.tsx
> +          </Listbox.Options>
ここはフォーカス当たるとアウトライン出ますが、Electron はオレンジなんですよね。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/components/Button/style.css.ts
> +  lineHeight: 1,
[IMO]
`lineHeight: 1` ですが、テキストに改行あった時のことを考えると付けたくないですね。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +            <div>{repository}</div>
[MUST]
`<div>{repository}</div>` は `p` 要素の方がふさわしいです。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
[MUST]
やれる範囲で a11y 。
`button` 要素にタブキーでフォーカスが当たった時にアウトラインが表示されていません。

色は現状仮なのですが、theme.css に書いてある `themeFocusVisibleOutline` というクラスをつけることで、`:focus-visible` の時にアウトライン代わりの装飾を付けれます。

2021-08-16 11:49 UTC, mojahige commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
[MUST]
やれる範囲で a11y 。
`button` 要素にラベルがないので何をするためのボタンかわからないことになります。

ここだと `title` 属性で 「{リポジトリ名}を追加する」や「{リポジトリ名}を削除する」を指定するのが良いと思います。

2021-08-16 12:13 UTC, t-yng commented on renderer/src/components/AccountSelect/style.css.ts
> +  width: '100%',
気づかなかったです！
1b47a30

2021-08-16 12:15 UTC, t-yng commented on renderer/src/components/AccountSelect/AccountSelect.spec.tsx
> +    it('配列先頭のアカウントが初期表示すること', () => {
ありがとうございます！
修正しました〜
21f884f

2021-08-16 12:34 UTC, t-yng commented on renderer/src/components/AccountSelect/AccountSelect.tsx
> +          </Listbox.Button>
対応しました〜
cf91a50

2021-08-16 12:36 UTC, t-yng commented on renderer/src/components/RepositorySearchBox/RepositorySearchBox.tsx
> +      </div>
input要素にフォーカスが当たっていることは、カーソル表示でフォーカスが当たっていることで分かるので、アウトラインを表示するのは違和感があるなと思いましたが、どうですか？

2021-08-16 12:47 UTC, mojahige commented on renderer/src/components/RepositorySearchBox/RepositorySearchBox.tsx
> +      </div>
こういう時はネイティブの input 要素の表現に合わせるのが一番良いと思ってまして、そうなると「カーソルが表示されていてアウトラインが表示される」なんですよね。

でもまぁ...無くても良いのかな。意味はわからないですが Slack とかカーソルだけですしね。
（自分はそっちが違和感あるんですが）

2021-08-16 12:51 UTC, mojahige commented on renderer/src/components/RepositorySearchBox/RepositorySearchBox.tsx
> +      </div>
余談ですが、Electron 内は `:focus` がデフォルトで無く、自分は `:focus-visible` にスタイルを当ててます。

2021-08-16 13:13 UTC, t-yng commented on renderer/src/components/AccountSelect/AccountSelect.tsx
> +          </Listbox.Options>
代わりにフォーカスのアウトラインを非表示にしました。
追加でカーソル移動のデザインを追加対応しました。
61e20bd

2021-08-16 13:15 UTC, t-yng commented on renderer/src/components/RepositorySearchBox/RepositorySearchBox.tsx
> +      </div>
アウトライン系はグローバルなCSSで対応してしまった方が良さそうですね

2021-08-16 13:19 UTC, t-yng commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +            <div>{repository}</div>
なるほどです！
cdc8fc7

2021-08-16 13:31 UTC, mojahige commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +            <div>{repository}</div>
すいません！
`<li>` の中にいますし `<div>` でも良いですね 🌝
`<li>` で囲われている段階で「リストの項目」って意味ですしね。

2021-08-16 13:33 UTC, t-yng commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
ボタンにアウトライン追加しました〜
ここも共通でボタン要素に対してスタイリングしてしまいたいですね。
3b50d24

2021-08-16 13:43 UTC, mojahige commented on renderer/src/theme.css.ts
> +    green: '#0A9710',
後で CSS 見直したいのでその時になんかしましょう〜

2021-08-16 13:54 UTC, t-yng commented on renderer/src/components/Button/style.css.ts
> +  lineHeight: 1,
なるほどー
`lintHeight: 1.5`にしてみました。
e99d255

2021-08-16 13:54 UTC, t-yng commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
`title` 追加しました〜
b5a757e8360d2e53e09b004f995437e8c40aae8d

2021-08-16 14:05 UTC, mojahige requested changes

2021-08-16 14:05 UTC, mojahige commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
[MUST]
b5a757e の変更で title 追加してくれてますが、文言が逆です〜。

`subscribedRepositories.includes` で true なら削除文言ですね 👀

2021-08-17 04:30 UTC, t-yng commented on renderer/src/pages/SelectRepositoryPage/SelectRepositoryPage.tsx
> +              </button>
ほんとですね 👀
修正しました〜
681fef7

2021-08-17 04:31 UTC, mojahige approved these changes
ϵ( 'Θ' )϶ < LGTM!!

2021-08-17 04:32 UTC, merged

2021-08-17 04:32 UTC, t-yng commented
ϵ( 'Θ' )϶ < Merge done !!